// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Ide3ouoV4DiclxkjwAM_f1rCueC0mRo',
    appId: '1:430724198070:web:5efefcb3e03519f1698017',
    messagingSenderId: '430724198070',
    projectId: 'flutter-chat-f3a08',
    authDomain: 'flutter-chat-f3a08.firebaseapp.com',
    databaseURL: 'https://flutter-chat-f3a08-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-f3a08.appspot.com',
    measurementId: 'G-F8KM7WKHMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhxhM_5PlvGk9IE-DLLeLzDQ1ldQKHzRg',
    appId: '1:430724198070:android:1eac49b5f8e3f734698017',
    messagingSenderId: '430724198070',
    projectId: 'flutter-chat-f3a08',
    databaseURL: 'https://flutter-chat-f3a08-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-f3a08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkJP3A3TUDuMxYkdQCdm9hCOsPTA_bM5g',
    appId: '1:430724198070:ios:9665791c3486a4fc698017',
    messagingSenderId: '430724198070',
    projectId: 'flutter-chat-f3a08',
    databaseURL: 'https://flutter-chat-f3a08-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-f3a08.appspot.com',
    iosClientId: '430724198070-4hu8a2umup404o4djshl4bhl5j6qaksb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkJP3A3TUDuMxYkdQCdm9hCOsPTA_bM5g',
    appId: '1:430724198070:ios:6974bf9228a02152698017',
    messagingSenderId: '430724198070',
    projectId: 'flutter-chat-f3a08',
    databaseURL: 'https://flutter-chat-f3a08-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-f3a08.appspot.com',
    iosClientId: '430724198070-eng9tiufkc1qj60062ao4dc6cctu8gl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp.RunnerTests',
  );
}
